- android/src/main/java/app/notifee/core/ReceiverService.java
> fix(android): make certain request codes are unique in ReceiverService

- .gitignore
- packages/react-native/example/.flowconfig
- packages/react-native/example/.gitignore
- packages/react-native/example/android/app/build.gradle
- packages/react-native/example/android/app/src/main/res/values/styles.xml
- packages/react-native/example/android/build.gradle
- packages/react-native/example/android/gradle.properties
- packages/react-native/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/react-native/example/android/gradlew
- packages/react-native/example/android/gradlew.bat
- packages/react-native/example/ios/Podfile
- packages/react-native/example/ios/Podfile.lock
- packages/react-native/example/ios/example.xcodeproj/project.pbxproj
- packages/react-native/example/package.json
- packages/react-native/refresh-example.sh
As part of responding to #179 I worked on https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh (which works now) and I double-checked the example, which I found to be just a bit out of date, and the refresh-example script wasn't quite working with current notifee
So I updated the example app, tested it locally, and here's the working version
> docs(example): make sure example builds correctly

- android/build.gradle
- android/src/main/AndroidManifest.xml
- packages/react-native/android/build.gradle
- tests_react_native/android/app/src/main/AndroidManifest.xml
- tests_react_native/android/build.gradle
All receivers and activities must have an `android:exported` declaration
> feat(android): support Android 12

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- .github/workflows/tests_jest.yml
- .github/workflows/tests_junit.yml
- android/src/main/java/app/notifee/core/NotifeeConfig.java
- android/src/main/java/app/notifee/core/NotificationManager.java
- android/src/main/java/app/notifee/core/ReceiverService.java
- ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.m
- ios/NotifeeCore/NotifeeCore.m
- ios/NotifeeCore/NotifeeCoreExtensionHelper.m
- ios/NotifeeCore/NotifeeCoreUtil.m
- package.json
- packages/react-native/example/README.md
- packages/react-native/example/ios/example/AppDelegate.h
- packages/react-native/example/ios/example/AppDelegate.m
- packages/react-native/example/ios/example/main.m
- packages/react-native/example/ios/exampleTests/exampleTests.m
- packages/react-native/ios/RNNotifee/NotifeeApiModule.h
- packages/react-native/ios/RNNotifee/NotifeeApiModule.m
- tests_react_native/ios/Podfile.lock
- tests_react_native/ios/testing.xcodeproj/project.pbxproj
- tests_react_native/ios/testing/main.m
This fixes #212 
Also fixes an irritating install issue
Also commits current podfile lock
Also handles default branch rename to main
Also does a format run
All as separate commits - each should be reviewed separately, whole thing should be rebase-merged
> fix(ios, badging): specify nonnull on ios badge arguments

- .github/workflows/docs_deployment.yml
- .github/workflows/tests_e2e_ios.yml
A trigger to update the website when docs have changed
> ci: github action to trigger docs deployment

- docs/react-native/docs/release-notes.md
There was some confusion on what was affected and what to do.
I'm not 100% certain I'm making it better with this, I welcome any word-smithery in review
> docs(release-notes): update change note for v4.0.0

- docs/react-native/docs/ios/badges.md
Change Increment with Decrement
> docs: update badges.md

- android/build.gradle
- packages/react-native/android/build.gradle
> build(android): upgrade version of play services tasks

- docs/react-native/docs/ios/remote-notification-support.md
as mentioned here
https://github.com/invertase/notifee/issues/277#issuecomment-1044679232
> fix: specify required casing for APNS payload params

- docs/react-native/docs/installation.md
> docs: minor grammar fix in installation.md

- android/src/main/java/app/notifee/core/model/IntervalTriggerModel.java
- android/src/main/java/app/notifee/core/model/NotificationAndroidModel.java
- android/src/main/java/app/notifee/core/model/NotificationAndroidStyleModel.java
- android/src/main/java/app/notifee/core/model/TimestampTriggerModel.java
- android/src/main/java/app/notifee/core/utility/ObjectUtils.java
A continuation of https://github.com/invertase/notifee/pull/425
To be able to handle both flutter and react-native packages
> fix: android double conversion

- android/src/main/java/app/notifee/core/NotifeeAlarmManager.java
- android/src/main/java/app/notifee/core/model/TimestampTriggerModel.java
Partial solution (if not full solution) for #422
> fix(android): ensure trigger notification is rescheduled in the future

- android/src/main/java/app/notifee/core/NotifeeAlarmManager.java
- android/src/main/java/app/notifee/core/model/TimestampTriggerModel.java
> fix(android): prevent error when creating a repeating trigger notification

- docs-react-native/react-native/docs/ios/behaviour.md
- ios/NotifeeCore/NotifeeCore.m
- packages/react-native/src/types/NotificationIOS.ts
- packages/react-native/src/validators/validateIOSNotification.ts
- Add support for iOS 15 interruptionLevel
- Fix #287
> feat(ios): support interruptionLevel

- README.md
Removed some errors from the Readme File to improve readability!
> docs(README): fix grammatical errors

- packages/react-native/android/build.gradle
This PR is a fix for #547 #543
> feat(android): update the compileSdkVersion and targetSdkVersion in android build.gradle to fix compile issues

- docs-react-native/react-native/docs/android/appearance.md
I needed to display base64 images and the edit to the largeIcon worked for me. I would like to believe it may help someone else who might be stuck.
> Proposed appearance.md

- docs-react-native/react-native/docs/triggers.md
> docs(triggers): Update Android 12+ trigger permissions example

- packages/react-native/src/validators/iosCommunicationInfo/validateIOSCommunicationInfoPerson.ts
As noticed by @lluiscab at https://github.com/invertase/notifee/pull/526#issuecomment-1352804733
> fix: remove console.log statement

- packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeApiModule.java
Just fixed a typo in the comments.
> chore: fixed typo

- android/build.gradle
- packages/flutter/packages/notifee/android/build.gradle
- packages/react-native/android/build.gradle
> chore(deps): Update EventBus to 3.3.1

- docs-react-native/react-native/docs/android/foreground-service.md
Its looks like lost `async` declare
> docs: update foreground-service docs

- android/build.gradle
- packages/react-native/android/build.gradle
To help resolve #699
Still waiting on feedback from author but we do no longer need this dependency since licensing was removed
> chore: remove unused android dependency

- docs-react-native/react-native/docs/installation.md
There is small typo in installation.md, this PR to fix it.
> docs: fix typo in installation.md

- docs-react-native/react-native/docs/installation.md
> docs: using latest expo cli for installation in the documentation

- ios/NotifeeCore/NotifeeCore.m
- ios/NotifeeCore/NotifeeCoreExtensionHelper.m
- ios/NotifeeCore/NotifeeCoreUtil.h
- ios/NotifeeCore/NotifeeCoreUtil.m
Cachig the avatar image in Communication Notification  using existing caching logic.
And also rename the function correctly
> feat(ios): Caching image in Communication Notification

- packages/react-native/example/package.json
> chore: update example app to use 7.8.0

- docs-react-native/react-native/docs/android/permissions.md
- tests_react_native/example/app.tsx
This picks up where #661 left off and includes the feedback from @helenaford
> docs: Updates Android permissions docs

- docs-react-native/react-native/docs/android/behaviour.md
I kinda strugled to get fullscreen notifications working, and these 2 little tips could help people get them up and running in the future 😄
1. Specified the path of the file where <activity> needs to be altered
2. Made a warning to run ./gradlew clean and reinstall the app to get the new manifest
> docs: behaviour.md - useful fullscreen tips

- tests_react_native/__tests__/validators/validateIOSNotification.test.ts
- tests_react_native/example/notifications.ts
The current main is breaking because of lint issues. 
I just ran lint fix on the two files in question.
> fix: Run lint fix on two files so build doesn't break

- docs-react-native/react-native/docs/android/behaviour.md
> docs(android): note apps must now manually add USE_FULL_SCREEN_INTENT if needed

- docs-react-native/react-native/docs/android/foreground-service.md
This is the layout i had to use for the project to build
> docs: update foreground-service.md
