invertase/notifee

android/src/main/java/app/notifee/core/NotificationManager.java
Add more details why we parse 0 as an integer when cancelling a notification with id of "0" and remove unused method `cancelNotification` in `NotificationManager.java`
=> chore: code comment for cancelling fcm notifications on android

docs/react-native/docs/ios/remote-notification-support.md
including / not including foregroundPresentationOptions makes a big difference because by default the notification will not be shown when presented while the app is in the foreground, as seen in https://github.com/invertase/notifee/pull/169
=> docs: add foregroundPresentationOptions for remote PN

packages/react-native/android/build.gradle
buildtools 31.0.0 only works with gradle 7+
using buildtools 30.0.3 should work with gradle plugin 4.2+ and gradle 7+
Fixes #211 based on feedback from the issue, this version should work
=> fix(android, build-tools): use more backwards-compatible buildtools

CONTRIBUTING.md
Added missing points to the release notes, including updating the website after we modify the docs.
Not sure how much detail to go into about redeploying the website. I think we could look into how we create a GitHub Action that auto-deploys when the docs directory is updated
=> docs(CONTRIBUTING): update release checklist

.github/workflows/tests_e2e_ios.yml
There was a failure where the ios simulator video took a 500 error when uploading.
That's interesting, but not in our control, so it should not fail the build.
=> test(e2e, ios): artifact uploads should not fail workflow

docs/react-native/docs/triggers.md
A repeating timestamp trigger on iOS does not work the same as Android.
Hopefully, this update gives more clarity and understanding of how it does works.
Fixes https://github.com/invertase/notifee/issues/215
=> docs(ios, triggers): update explanation of how a repeating timestamp trigger works

docs/react-native/docs/triggers.md
I've updated this doc to reflect correct trigger timestamp from commented description ("fire in 3 hours") as it has to be in milliseconds not in seconds (10800).
=> docs(triggers): update example with timestamp in milliseconds

.github/workflows/linting.yml, .github/workflows/tests_e2e_android.yml, .github/workflows/tests_e2e_ios.yml, .github/workflows/tests_jest.yml, .github/workflows/tests_junit.yml
Update triggers so that a job is only run once at a time - either for a pull request or for a push to main (not both)
=> chore: update GitHub action triggers

android/src/main/AndroidManifest.xml, android/src/main/java/app/notifee/core/ReceiverService.java
There's an issue currently where if an action is performed on a notification, the notification drawer remains open and the notification isn't canceled (unlike when a notification is pressed).
Closes https://github.com/invertase/notifee/issues/268
TODO:
Test on Android 12
=> fix(android): auto cancel and close notification drawer when action is pressed

docs/react-native/docs/ios/remote-notification-support.md
When implementing a Notification Service Extension, I run into an issue -> when following the steps from the documentation, the extension was not working for me.
What made the feature work for me, was setting the **deployments target** properties to the same values in both may app target and in newly created extension. Thus, I guess it would be nice to mention it to the users :) What do you think?
=> docs: [Notification Service Extension] Add a hint on required matching deployment target values

android/src/main/java/app/notifee/core/NotificationManager.java
Hi,
I noticed that AlarmManager alarms are never getting canceled because `Continuation` object's tasks, in `NotifeeAlarmManager.cancelAllNotifications()`, is never running.
It's silently throwing errors (please see screenshot below) for the older Android versions and not causing big trouble because the data in local db is getting removed in `NotificationManager.cancelAllNotifications` , and the PN can not be sent without the data. However, it's causing to [this error](https://github.com/invertase/notifee/issues/349) for `Android >=12`.
Fixes #349
Hope this changes makes sense.
=> fix(android): ensure alarmManager notifications are cancelled

docs/react-native/docs/installation.md, packages/react-native/plugin/__tests__/__snapshots__/androidProjectBuild.test.ts.snap, packages/react-native/plugin/__tests__/__snapshots__/fullPlugin.test.ts.snap, packages/react-native/plugin/__tests__/androidProjectBuild.test.ts, packages/react-native/plugin/__tests__/fullPlugin.test.ts, packages/react-native/plugin/src/withNotifeeProjectGradlePlugin.ts, tests_react_native/jest.config.js
As mentioned in #314 the current version of Notifee does not build when using expo managed app with the expo plugin as the default `compileSdkVersion` is 30 and Notifee needs 31. Also EAS is using JDK 8 by default and using compileSdkVersion 31 requires the build to be done with JDK 11.
- Expo plugin: Increase compileSdkVersion to 31 in project gradle file if the initial version is 30
- Expo installation documentation: Add a note about the required JDK 11 and the `eas.json` configuration to use JDK 11.
ref #314
=> fix(expo): increase compileSdkVersion to 31 and add EAS instructions to doc

packages/react-native/.npmignore, packages/react-native/src/NotifeeApiModule.ts, packages/react-native/src/NotifeeNativeModule.web.ts, packages/react-native/src/types/Notification.ts, packages/react-native/src/types/NotificationWeb.ts, packages/react-native/src/utils/index.ts, packages/react-native/src/validators/validateAndroidNotification.ts, packages/react-native/src/validators/validateAndroidStyle.ts, packages/react-native/src/validators/validateIOSAttachment.ts, tests_react_native/__tests__/NotifeeApiModule.test.ts
There are no actual APIs productively implemented, however the structure for react-native-web support is in place now, and it builds correctly and runs on react-native-web without failures, so notifee may safely be included in react-native-web projects
Demonstration:
https://github.com/mikehardy/rnfbdemo/commit/d0f7ef9745ef0aa1981919562927cad66af298b5
Clean console from `yarn web` in `notifeewebdemo` on that commit of my demo script:
As discussed in https://github.com/invertase/notifee/discussions/364 with @thecompoundingdev as well as on Slack with @yamankatby and @Ehesp
=> feat(web): basic support for react-native-web

packages/react-native/android/build.gradle
1. The android app project name could be different than `:app`
2. There could be more than one app projects under android main projects
After this patch, one could specify a global variable `reactNativeProjects` in their project configuration and it should work in both the above situations.
e.g. I have 2 projects `:client` and `:server`
```gradle
buildscript {
ext {
// ...
reactNativeProjects = [':client', ':server']
}
// ....
}
```
=> fix(android): allow the projects to specify names of their apps

packages/react-native/android/build.gradle
I can't seem to build my react native project using notifee on version `5.2.0`. I'm getting a syntax error/unexpected token it seems. This will fix the issue and gradle builds successfully.
> startup failed:
build file 'node_modules/@notifee/react-native/android/build.gradle': 22: unexpected token: -> @ line 22, column 38.
reactNativeProjects.each(dependent -> project.evaluationDependsOn(dependent))
=> fix(android): build.gradle unexpected token

packages/react-native/jest-mock.js
NotificationSettings have been changed in 5.1.0. This was not reflected in jest-mock.js and breaks tests.
This PR fixes this and exposes `AndroidNotificationSetting` and `TriggerType`
=> fix(test, jest): changes in release 5.1.0 not reflected in jest-mock

packages/react-native/package.json
This was causing an error locally to develop the library, fixing to major working (2.0.0) did not work, so removing the dev dep for now
=> chore: remove path-exists to prevent error on install

docs/react-native/docs/triggers.md
Hey there, 
I noticed the casing was capitalized for the Android Permission section when it is lower cased for the remaining parts of the documentation. 
This initially confused me thinking there was an instance of notifee that needed to be created. 
I'm purposing this change to prevent future confusion.
=> docs: change casing of notifee import to lowercase

packages/react-native/src/types/Module.ts
Deleted "removes removes" duplicate in [cancelNotification API](https://notifee.app/react-native/reference/cancelnotification)
The cancelNotification API removes removes any displayed notifications... to The cancelNotification API removes any displayed notifications...
Related issue: https://github.com/invertase/notifee/issues/411
=> docs: removed duplicate in cancelNotification API

docs/react-native/docs/installation.md, packages/react-native/android/build.gradle, packages/react-native/example/android/build.gradle, packages/react-native/example/package.json, packages/react-native/plugin/__tests__/__snapshots__/androidProjectBuild.test.ts.snap, packages/react-native/plugin/__tests__/androidProjectBuild.test.ts, packages/react-native/plugin/src/withNotifeeProjectGradlePlugin.ts, tests_react_native/android/build.gradle, tests_react_native/ios/Podfile.lock
Hello Team, thank you for always supporting high-quality open source!
I got the idea from [react-native-gradle](https://github.com/invertase/react-native-gradle-plugin/blob/master/src/main/groovy/io/invertase/gradle/build/ReactNativeModule.groovy#L128-L134) and simplifies the installation.
It works, but I'm not sure of any side effects because I don't have deep knowledge of groovy.
so feel free to comment. thank you!
=> feat(android): simple installation

docs-react-native/react-native/docs/integrations/onesignal.md
I've just done a OneSignal + Notifee integration in our app and the dependency exclusion is no longer needed with the 4.0.0+ versions.
=> docs: Update OneSignal integration docs

android/src/main/AndroidManifest.xml
For Xiaomi devices,  heads-up notifications are disabled. By adding this permission resolves the issue.
Fixes #296
=> fix: add `ACCESS_NOTIFICATION_POLICY` android user-permission

docs-react-native/react-native/docs/displaying-a-notification.md
Hopefully, this will clear up some confusion around the required steps needed for some common scenarios:
- displaying a notification on iOS, requires requesting permission
- `pressAction` is needed on Android to open the app when a notification is pressed
=> docs: improve docs on how to initially display a notification

packages/react-native/android/build.gradle
may resolve monorepo issues (https://github.com/invertase/notifee/issues/350#issuecomment-1152308755, https://github.com/invertase/notifee/issues/350#issuecomment-1172638425)
=> fix(android): find the module recursively

docs-react-native/react-native/docs/ios/appearance.md, docs-react-native/react-native/docs/ios/remote-notification-support.md, ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.m, packages/flutter/packages/notifee_platform_interface/lib/src/models/notification/ios/foreground_presentation_options.dart, packages/flutter/packages/notifee_platform_interface/lib/src/models/notification/notification_ios.dart, packages/react-native/src/types/NotificationIOS.ts, packages/react-native/src/validators/validateIOSNotification.ts, tests_react_native/__tests__/validators/validateIOSNotification.test.ts, tests_react_native/__tests__/validators/validateNotifications.test.ts
`UNNotificationPresentationOptionAlert` is deprecated in iOS 14 and Apple recommends to use `UNNotificationPresentationOptionList` and `UNNotificationPresentationOptionBanner`.
Thus, I added `list` and `banner` compatibility for iOS.
-----
* [UNNotificationPresentationOptionAlert | Apple Developer Documentation](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/unnotificationpresentationoptionalert)
=> feat(ios): Add `banner` and `list` options to `IOSForegroundPresentationOptions`

docs-react-native/react-native/docs/ios/remote-notification-support.md
Added warning about mutable-content requirement for NSE to work and also about content-available so the notifications works when app is in foreground.
Also edited section for Edit Payload to include second option on how to edit the payload. Second option is kind of better imho as BE do not need to care too much about FE implementation and it will be easier to switch to other libs - only FE needs to update the code and BE can stay same
=> docs: Update remote-notification-support.md

docs-react-native/react-native/docs/ios/appearance.md, ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.m, packages/flutter/packages/notifee_platform_interface/lib/src/models/notification/notification_ios.dart, packages/react-native/README.md, packages/react-native/src/types/NotificationIOS.ts, packages/react-native/src/validators/validateIOSNotification.ts
See discussions on https://github.com/invertase/notifee/pull/465
Deprecates .alert from foregroundPresentationOptions
Should not have any breaking changes
- Users should remove .alert from their payload and use .list and .banner instead if they are setting custom foregroundPresentationOptions
- Users can still use .alert, it is only deprecated
=> feat: deprecate foregroundPresentationOptions.alert

packages/react-native/android/build.gradle
Ensure the link to specific lines of the RN build.gradle doesn't get out of sync as further edits are made to the file
=> chore: expand URL to its canonical form

docs-react-native/react-native/docs/android/permissions.md
The link to the channels page here is broken: https://notifee.app/react-native/docs/android/permissions
By adding a slash in front of the link it leads to the right site.
=> docs: fix link to android channels

docs-react-native/react-native/docs/triggers.md
I'm not sure on the Android 50 timestamp trigger count limit though, on stackoverflow I only see limits of 500 and only on Samsung devices.
What's the source / experience on 50 as the limit so we can link it?
https://stackoverflow.com/questions/29344971/java-lang-securityexception-too-many-alarms-500-registered-from-pid-10790-u?noredirect=1&lq=1
This is cribbed from here - it comes up a lot, seems it should be in the docs: https://github.com/invertase/notifee/issues/488#issuecomment-1211849875
=> docs(triggers): add information on maximum timestamp counts

packages/react-native/src/validators/validateAndroidAction.ts, packages/react-native/src/validators/validateIOSCategoryAction.ts
Hello!
Currently, we're getting warnings in our project, due to: 
- `validateAndroidAction` getting type `true | AndroidInput` instead of `AndroidInput`
- `validateIOSCategoryAction` getting type `true | IOSInput` instead of `IOSInput`
I've simplified code to make it check if `action.input` strictly equals to `true`, instead of checking if it's boolean and if it's truthy.
This seems more robust and easily readable, plus it's not complaining anymore.
Comments welcome, as again, I might be in the wrong here :)
=> fix: validate category action input ts errors

android/build.gradle
There's an issue with Apple Silicon and this older version of room, newer version fixes this issue.
Also, there's a bunch of fixes with the current stable version.
Error log before fix:
```
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
at androidx.room.verifier.DatabaseVerifier.<clinit>(DatabaseVerifier.kt:71)
```
=> chore: bump version of android dependency

docs-react-native/react-native/docs/installation.md
Added information about specifying compileSdkVersion & targetSdkVersion to the installation instructions.
=> docs(android): Information about specifying compileSdkVersion & targetSdkVersion

packages/react-native/src/types/Notification.ts
Change from `boolean` to include the keys added here: https://github.com/invertase/notifee/blob/main/ios/NotifeeCore/NotifeeCoreUtil.m#L589-L599
=> fix: Add keys to `remote` type

android/src/main/java/app/notifee/core/Notifee.java, packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeApiModule.java
Closes #555
- Fixes an issue where sometimes the permissions activity is null when requesting permissions on Android, which appears to only be an issue for Android 11 and below. 
- As a precaution, we will return notification settings for devices 12 or lower, in addition to checking if the activity is null before calling requestPermissions.
- Also added more code comments and logger messages
=> fix(android): fix an issue when requesting permissions for Android 12 or lower

packages/react-native/plugin/src/withNotifeeProjectGradlePlugin.ts
Bumps compileSdkVersion from 31 to 33 for expo plugin
Closes #564
Related https://github.com/expo/expo/issues/19385
=> fix(expo): bump compileSdkVersion for expo plugin to 33

packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeReactUtils.java, tests_react_native/example/notifications.ts, tests_react_native/index.test.js, tests_react_native/specs/notification.spec.ts
This PR fixes two issues:
1. Issue with registering in `test_react_native/example`.
Because `AndroidFlags` was imported with `'@notifee/react-native/src'` and everything else was imported `'@notifee/react-native'` it caused double initialization of NotifeeApiModule which caused the following errors showing when `yarn tests_rn:android:test` is run:
```
WARN  registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'app.notifee.foreground-service-headless-task'
WARN  registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'app.notifee.notification-event'
WARN  [notifee] no background event handler has been set. Set a handler via the "onBackgroundEvent" method.
```
2. Issue with Quick Action tap not being handled on Android …
=> fix: isAppInForeground

.github/workflows/stale.yml
Noticed previous stale bot was simply not performing in react-native-firebase, and scanned around for other related repos that needed an update
Turns out this repo does not even have a stale bot, but it really should as we do rely on community contributions so much here
So here's a config that works for react-native-firebase (verbatim, no changes)
Note that labels may need a change (or...perhaps best to update them?)
- add 'Type: Stale' for the bot
- add '📌 pin' as a keep open
- add 'Blocked: Needs Review' as a keep open
- add 'Help: Good First Issue' as a keep open
=> ci(stale): add stale workflow

android/src/main/java/app/notifee/core/NotificationReceiverHandler.java
Hi, I have noticed I don't get any press actions on the initial notification event, after some debugging with LogCat I found handleNotificationPressIntent doesn't have InitialNotificationEvent.
tested version "@notifee/react-native": "^7.1.0"
https://github.com/invertase/notifee/issues/546
=> fix(android): set initial notification for quick actions

android/src/main/java/app/notifee/core/ReceiverService.java
Closes #579
Despite what android docs say, we should check for the application sdk version and not the target sdk version when determining if the notification drawer should be closed
=> fix: android 11 close notificaiton drawer for quick actions

android/src/main/java/app/notifee/core/ForegroundService.java, android/src/main/java/app/notifee/core/NotificationManager.java, android/src/main/java/app/notifee/core/event/NotificationEvent.java, packages/react-native/src/types/Notification.ts
closes #631 and #630
this adds a new event type for android, which will be sent if android tries to push a notification as foreground service, but a foreground service already exist
this allows to detect and show a different notification when a foreground service is active and a new one cannot be started
I did not know how to add this to the docs (didn't find a markdown file, so I guess it's auto generated ?)
=> feat(android): add TYPE_FG_ALREADY_EXIST event type

android/src/main/java/app/notifee/core/model/NotificationAndroidModel.java, tests_react_native/example/notifications.ts
Closes #618. From debugging, a null exception was thrown when a trigger notification was being processed with a lights array, and when that lights array contains a string value for a color (e.g. 'purple'). 
The notification however is displayed correctly via `displayNotification`.
The original issue described it was an Android 13 thing which it quite possibly be.
Either way, whether the notification is displayed via `notifee.displayNotification` or `notifee.createTriggerNotification`, fundamentally the code was wrong as the lights array can include strings as well as integers.  First one being a string, second and third being a number. 
Also, for additional safety, added a try/catch.
=> fix: parsing lights for trigger notifications with colors as strings

android/src/main/java/app/notifee/core/NotificationReceiverHandler.java, tests_react_native/example/notifications.ts
Fixes an issue where if autoCancel is set to `false`, for android actions this is ignored and we are in fact canceling the notification once the action is handled.
We have this behaviour for android 11 and below, but it was missing for android 12 and above.
Fixes #697
=> fix(android): auto cancel with actions

android/build.gradle, android/src/main/java/app/notifee/core/NotificationManager.java, packages/react-native/android/build.gradle
Fixes #696
- Interval triggers was missing initial delay
- Upgrades work manager and room db - there's no breaking changes and will help with maintenance 
- With work manager update, it's advised that `ExistingPeriodicWorkPolicy.REPLACE` is changed to `ExistingPeriodicWorkPolicy.UPDATE`
=> fix(android): prevent interval triggers from firing immediately

android/src/main/java/app/notifee/core/NotificationPendingIntent.java
Fixes https://github.com/invertase/notifee/issues/637 https://github.com/invertase/notifee/issues/651
- uniqueId was always started from 0. As a result, uniqueId was sometimes duplicated
- uses uuid now to get a random number
thanks to @hibinoA for his help and contribution to fixing this issue
=> fix(android): pending intent unique id

packages/react-native/src/types/Notification.ts
The Notification interface **data** property type changed in [this](https://github.com/invertase/notifee/commit/32bce631a953eecd4211d0824ebf0940ba2e2b83#diff-0387e7fb23ad1a9deceecda23956f9e21006003f11f894eab30cd7f45428b118) pull request.
Values stored in the **data** object are no longer only strings according to the type.
This pull request changes the **data** property documentation to reflect the change
=> docs: fixing Notification data parameter type

ios/NotifeeCore/NotifeeCore+NSNotificationCenter.m, ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.h, ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.m, ios/NotifeeCore/NotifeeCore.m, packages/flutter/packages/notifee/example/lib/main.dart, packages/flutter/packages/notifee/ios/Classes/NotifeePluginSwift.swift
Improves getInitialNotification for iOS as well as implementing it for Flutter. 
Even though it's not technically needed as there is an onForegroundEvent, it seems from the community feedback it is useful to keep.
=> feat(flutter): initial notification for iOS

ios/NotifeeCore/NotifeeCore.m
Thank you for this great library!
This pr is to not block the ui thread on iOS when sending attachments that needs to be downloaded before sending the notification. We experienced this and found #234 describing exactly the issue we had.
=> feat(iOS): run create and display notification in background thread

.github/workflows/flutter_checks.yml, .github/workflows/linting.yml, .github/workflows/pr_title.yml, .github/workflows/scripts/validate-formatting.sh, .github/workflows/stale.yml, .github/workflows/tests_e2e_android.yml, .github/workflows/tests_e2e_ios.yml, .github/workflows/tests_jest.yml, .github/workflows/tests_junit.yml, package.json, packages/react-native/example/ios/Podfile, packages/react-native/example/ios/Podfile.lock, packages/react-native/example/ios/example.xcodeproj/project.pbxproj, packages/react-native/example/package.json, tests_react_native/ios/Podfile.lock, tests_react_native/specs/notification.spec.ts
Goals:
This should unblock the ability to verify community PRs that have been stagnant a while
=> build(deps): various dependency updates

ios/NotifeeCore/NotifeeCoreUtil.m, packages/react-native/src/types/NotificationIOS.ts, packages/react-native/src/validators/iosCommunicationInfo/validateIOSCommunicationInfo.ts, tests_react_native/__tests__/validators/validateIOSNotification.test.ts, tests_react_native/example/notifications.ts, tests_react_native/sendPushNotification.js
Hey!
I was trying to add a subtitle/group name to my communication notifications and found out that notifee doesn't support it at the moment so in this PR I added support for it.
Related issues #889 #865
For context, here is an image of what I'm talking about:
=> feat: group support to communication notifications

packages/react-native/src/NotifeeNativeModule.ts
EventSubscriptionVendor type is no longer being exported https://github.com/facebook/react-native/blob/02f163e4e83c3676216cd9360166e1cb0a8eda5f/packages/react-native/types/index.d.ts#L153
=> fix: Remove EventSubscriptionVendor type use as it's removed in RN0.73

ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.m, package.json
Fixes
* #925
* #984
For notifications received when the app is backgrounded or killed in iOS (through `userNotificationCenter:didReceiveNotificationResponse:`), the original delegate is not invoked for non-Notifee notifications. The existing code attempts to parse the unknown notification into a format Notifee understands before giving the original delegate a chance to handle it.
I've moved up original delegate so that it handles a non-Notifee notification first (if it exists). If there is no original delegate, then we fall back to parsing the unknown notification and allowing Notifee to handle it.
1. Jest tests all pass
2. iOS end-to-end tests all pass
3. I have an app that handles both [Iterable](https://support.iterable.com/hc/en-us/articles/360035018152-Iterable-s-iOS-SDK#_7-5-handle-i …
=> fix(iOS): Allow the original delegate to handle non-Notifee notifications first

packages/react-native/src/types/Module.ts
cancelAllNotifications signature optional tag property is added. This is useful when we need to delete remote notifications
=> fix(types): add cancelAllNotifications optional android tag property

android/src/main/AndroidManifest.xml, packages/react-native/src/types/Notification.ts
Starting with Android 14 USE_FULL_SCREEN_INTENT is no longer allowed for most apps. It could be granted only to apps that provide calling and alarm functionalities.
A good way to solve this is to remove USE_FULL_SCREEN_INTENT by default and add a description for [NotificationFullScreenAction](https://notifee.app/react-native/reference/notificationfullscreenaction) that it needs `USE_FULL_SCREEN_INTENT`.
Please check if the docs show correctly because I've not found the way to run typedoc for that repo.
- Fixes #1027
- Fixes #1030
=> fix(android): Remove USE_FULL_SCREEN_INTENT as the default permission

packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeApiModule.java
invalidate is the new way to have a hook called when react-native instances are going away, but onCatalystInstanceDestroy is still required for compatibility with older react-native versions
=> fix(android): support invalidate alongside deprecated onCatalystInstanceDestroy

.github/workflows/linting.yml, .github/workflows/tests_e2e_android.yml, .github/workflows/tests_e2e_ios.yml, .github/workflows/tests_jest.yml, .github/workflows/tests_junit.yml, ios/NotifeeCore/NotifeeCore+NSNotificationCenter.m, ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.h, ios/NotifeeCore/NotifeeCore+UNUserNotificationCenter.m, ios/NotifeeCore/NotifeeCore.m, ios/NotifeeCore/NotifeeCoreUtil.m, package.json, packages/react-native/src/NotifeeNativeError.ts, packages/react-native/src/types/NotificationAndroid.ts, packages/react-native/src/utils/index.ts, packages/react-native/src/utils/validate.ts, packages/react-native/src/validators/validateAndroidNotification.ts, tests_react_native/example/app.tsx, tests_react_native/ios/Podfile.lock, tests_react_native/specs/api.spec.ts
Old workaround of using -1 on the application object no longer works
If iOS16+ use the new setBadge API and a real badge count of 0 and things appear to work
Also includes a series of commits that clean up lint errors all over, and fix up CI flakes
Peeled off from #510 as they were not related and that one will squash merge
=> fix(ios): use new badge APIs to correctly clear badge on iOS18+

android/build.gradle, packages/react-native/android/build.gradle
without this dep in the module build.gradle the transitive dep was absent in to the module so module users crashed on startup
also adopt guava 33.3.1 (current) vs 31.1
Fixes #1114
=> fix(android): add guava transitive dep to module deps

packages/react-native/jest-mock.js
Hi there,
Just a minor addition to the jest-mock for the react-native package.
The `createChannels` method was missing a mock implementation, which was a bit of a head-scratcher in tests until I tracked it down to here.
Cheers.
=> fix: Add missing createChannels mock.

packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeReactUtils.java
...but do so in a way that is backwards-compatible as the symbols required
- do not show up at all until react-native 0.73
- moved to different package names in 0.74
Test plan:
I used this script, on my react-native 0.76 testing branch, to verify that it worked:
https://github.com/mikehardy/rnfbdemo/blob/rn76/notifee-demo.sh
I verified it down to react-native 0.72 by changing this line to the various stable versions (0.75.4, 0.74.6, 0.73.10, 0.72.17):
https://github.com/mikehardy/rnfbdemo/blob/1064dcd31a031e9abb53f2611bf32fda5470ee28/notifee-demo.sh#L4
Of particular note is that it contains the patch which I propose here, and is what made things work, with a huge debt of gratitude to @Eclipses-Saros for the initial investigation, idea, and testing. My contribution was making it reflective …
=> fix(android): forward-port getReactContext to new arch bridgeless mode

packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeApiModule.java
This PR addresses a potential race condition in the `requestPermission` method within `NotifeeApiModule.java`. The issue likely arises when the `View` or `Activity` is no longer available due to a user dismissal or other lifecycle changes before the permission request can be completed. This can lead to a `NullPointerException` crash when the code tries to access the `View` or `Activity`.
In cases where the `View` or `Activity` is null by the time `requestPermission` is invoked, the lack of exception handling causes the app to crash. This PR wraps the permission request in a `try-catch` block to handle such scenarios gracefully and prevent crashes. Logging the exception provides a way to trace issues when they occur, and rejecting the promise enables the app code to manage the error …
=> fix(android): add error handling for POST_NOTIFICATIONS permission request (#1064)

docs-react-native/react-native/docs/installation.md, packages/react-native/android/proguard-rules.pro, packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeReactUtils.java
We use dynamic class-loading via reflection to determine if we are in new architecture mode or not and load the ReactContext
If we don't correctly preserve those names in minimization, we will crash in a new architecture context on release builds as the class names will have moved during the minimization
=> fix(android): preserve new-arch classnames used in backwards-compat logic

packages/react-native/android/src/main/java/io/invertase/notifee/HeadlessTask.java, packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeApiModule.java, packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeReactUtils.java, tests_react_native/example/app.tsx, tests_react_native/index.js, tests_react_native/ios/Podfile.lock
very tricky to make sure react-native is initialized during headlessJS startup so you don't beat it in the race to asking for a ReactContext before it exists
- startup is event-driven so you have to attach listeners
- startup has to run on main thread so you have to post runnables
- multiple tasks may come in while starting up, you must queue / drain
- startup objects / methods differ across react-native new / old arch
get all that right, and you'll have a valid ReactContext, without dropping any tasks that needed it before react-native was initialized
Previously, we were attempting to use a null ReactContext, resulting in errors from upstream headless services complaining about the context already being destroyed
Fixes #266
=> fix(android): fix headless crash with null ReactContext
